on: push
name: Публикация на empin-pro.ru
jobs:
  FTP-Deploy-Action:
    name: SSH-Deploy
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '--UPLOAD')"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.key }} # key - по-моему, так доолжен называться ключ в панели хостинга, где он добавляется
          ARGS: "-rc --delete"
          SOURCE: "/"
          REMOTE_HOST: 159.253.18.128
          REMOTE_USER: wow_vendor_team_usr
          TARGET: /var/www/wow_vendor_team_usr/data/www/events.vendorteam.ru
          EXCLUDE: "/node_modules/, /vendor/, /.env" # через запятую
