name: Публикация на events.vendorteam.ru

on:
  push

env:
  SERVER_HOST: 46.36.220.119
  SERVER_USER: events_usr
  SERVER_PATH: /var/www/events_usr/data/www/events.vendorteam.ru

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '--D')"
    steps:
      - uses: actions/checkout@v3

      # Install ssh key 
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.EV_VEN_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      # Deploy
      - run: rsync --exclude=/node_modules/ --exclude=/vendor/ --exclude=/.env --exclude=/.env.example  --exclude=/.editorconfig -rc --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
